item {
  id: 1
  name: 'apple'
}

item {
  id: 2
  name: 'banana'
}

item {
  id: 3
  name: 'beet'
}

item {
  id: 4
  name: 'bellpepper'
}

item {
  id: 5
  name: 'cabbage'
}

item {
  id: 6
  name: 'capsicum'
}

item {
  id: 7
  name: 'carrot'
}

item {
  id: 8
  name: 'cauliflower'
}

item {
  id: 9
  name: 'chillipepper'
}

item {
  id: 10
  name: 'corn'
}

item {
  id: 11
  name: 'cucumber'
}

item {
  id: 12
  name: 'eggplant'
}

item {
  id: 13
  name: 'garlic'
}

item {
  id: 14
  name: 'ginger'
}

item {
  id: 15
  name: 'grapes'
}

item {
  id: 16
  name: 'jalepeno'
}

item {
  id: 17
  name: 'kiwi'
}

item {
  id: 18
  name: 'lemon'
}

item {
  id: 19
  name: 'lettuce'
}

item {
  id: 20
  name: 'mango'
}

item {
  id: 21
  name: 'onion'
}

item {
  id: 22
  name: 'orange'
}

item {
  id: 23
  name: 'paprika'
}

item {
  id: 24
  name: 'pear'
}

item {
  id: 25
  name: 'peas'
}

item {
  id: 26
  name: 'pineapple'
}

item {
  id: 27
  name: 'pomegranate'
}

item {
  id: 28
  name: 'potato'
}

item {
  id: 29
  name: 'raddish'
}

item {
  id: 30
  name: 'soybeans'
}

item {
  id: 31
  name: 'spinach'
}

item {
  id: 32
  name: 'sweetcorn'
}

item {
  id: 33
  name: 'sweetpotato'
}

item {
  id: 34
  name: 'tomato'
}

item {
  id: 35
  name: 'turnip'
}

item {
  id: 36
  name: 'watermelon'
}

